### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by JDongian** [SrsBusiness/Party#3]
<pre>
$ make
clang -c -g -Wall -Iinclude --std=c11 src/search.c -o obj/search.o
src/search.c:13:10: fatal error: 'clock.h' file not found
#include "clock.h"
         ^
1 error generated.
Makefile:24: recipe for target 'obj/search.o' failed
make: *** [obj/search.o] Error 1
</pre>
What is `clock.h`?

**Comment by SrsBusiness** [comment]
Fixed.
